# Generated by Django 3.2 on 2021-06-13 05:57

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('user', 'user')
    for row in MyModel.objects.all():
        row.user_id = uuid.uuid4()
        row.save(update_fields=['user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
