# Generated by Django 3.2 on 2021-06-13 05:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_populate_user_id_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
