# Generated by Django 4.0.3 on 2022-04-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_profession'),
        ('user', '0004_remove_user_id_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.profession'),
        ),
    ]
