# Generated by Django 4.0.3 on 2022-04-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profession_link',
            new_name='profession',
        ),
    ]
