# Generated by Django 4.0.2 on 2022-03-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.state')),
            ],
        ),
    ]
